### PR TITLE
Moved to new csproj / netstandard / xunit / fake build

### PR DESCRIPTION
**Pull request by tebeco**
someone on slack wondered if it would work on netcore app and i had time to kill yesterday
i did not even took a look at the code just
just made it build / test

In order to release a clean SemVer you might want to remove the `<VersionSuffix>` line from the csproj
I used it so that the sample could reference `1.1.0-rc-*` so that every local build would resolve the lastest RC bits

it could be done magically with `Fake` by checking the current branch :
* Remove `<VersionSuffix>` from csproj
* current branch `master` ? no suffix => RTM will use the `VersionPrefix` from csproj
* custom branch ? add generate a `string` compliant with `SemVer` and use it in the `args` of `dotnet pack`

### CODE REVIEW

**Comment by roycornelissen** [comment]
I'd love to see this PR merged... looking for a .NET Standard version of this component. Also, for unit testability, it would be great if there would be `IObservableFileSystemWatcher` and `IFileDropWatcher` interfaces defined so they can be interchanged by mocks.

**Comment by tebeco** [comment]
keep in mind that this PR was made reaaaaally fast (too fast ?)

so it may contains actual issue ;)

**Comment by roycornelissen** [comment]
I actually migrated the solution to Net Standard myself too today, before I noticed that there is already this PR 😊 Unit tests work and it seems to be a viable way going forward. 

My take on it is here: https://github.com/roycornelissen/Rx-FileSystemWatcher

The commit: https://github.com/roycornelissen/Rx-FileSystemWatcher/commit/184504432b7b20a7b7f76408ecf04e3be4f750f2

The only thing I did not look into yet is the Rake file. But the basic migration I think is not so complex or risky.

**Comment by tebeco** [comment]
@roycornelissen 
Well, i made an arbitrary decison :
Since the project is a `dotnet` project, i used `Fake` (`FSharp`) to replace `Rake` (Ruby).
This felt more natural (Also i'm a total noob regarding `Ruby` / `Rake` 😄 )

It can now be installed as a cli :
* `dotnet tool install fake --tool-path .fake` (prefered way on CI)
* `dotnet tool install fake --global` (i general try to avoid global as it drives the version for everyone)

**Comment by tebeco** [comment]
@roycornelissen
i just took a look at @g0t4 activity on github
you probably want to forget this project completely ;)
(until you receive a mail from github)

you'd better keep you repo going on ;)

(same for @cyantic)

**Comment by roycornelissen** [comment]
@tebeco thanks, yeah I guess you are right. For now I've taken the source of the ObservableFileSystemWatcher and I'm using it in our project. Basically just 1 source file and a bunch of unit tests so I figured I could just adopt that code.

Perhaps either you or me could republish it as a new Nuget. Your solution seems more complete since you have updated the build scripts as well.

**Comment by tebeco** [comment]
just triple check on this repo that there is no potential Licensing and would only hurt yourself

if you want to publish it go for it.
i never tried to push nuget on nuget.org so then auth system will probably be new to me
i've only setup releases pipeline + preview for internal feed at work. it's probably a bit different

if you need a hand i could try to help

(a bit of context here ... someone asked on AspNetCore Comminuty about this package and i made a dumb attempt in about ~40min so triple check ^^)

**Comment by tebeco** [comment]
i wanted to open an issue on your fork for a scaffolding cleanup but ... it's a fork ^^

scaffolding ideas :
* .net speaking it is not usual to see `-` in repo name or in package name. you probably want to use either `.` or PascalCase
* Repo name could be the same name as the package name (for small name nuget / no mono repo for example)
* sln aside the build script (if 1 file only). Usually root folder if you are not using a mono repo.
* `src` only for sources and `test` folder only for test (these folder could seems overkill for only 1 src and 1 test project)
* TestProject + folder should have the same name as Tested project but ending with `.Tests` 
* same folder name as csproj name
* test class should _often_ have the same name as test class but ending with `Tests`

Just tell me if you create

**Pull request closed without merging**
